-- CreateTable
CREATE TABLE "piante_csv_raw" (
    "id" UUID NOT NULL,
    "plant_id" TEXT,
    "plant_code" TEXT,
    "botanical_name" TEXT,
    "common_name" TEXT,
    "previous_name" TEXT,
    "plant_type" TEXT,
    "water_needs" TEXT,
    "climate_zones" TEXT,
    "light_needs" TEXT,
    "soil_type" TEXT,
    "soil_additional" TEXT,
    "maintenance" TEXT,
    "abcission" TEXT,
    "height_ranges" TEXT,
    "spread_ranges" TEXT,
    "flower_colour" TEXT,
    "foliage_colour" TEXT,
    "perfume" TEXT,
    "aromatic" TEXT,
    "edible" TEXT,
    "bird_attracting" TEXT,
    "bird_attractant" TEXT,
    "bore_water_tolerance" TEXT,
    "frost_tolerance" TEXT,
    "greywater_tolerance" TEXT,
    "native" TEXT,
    "butterfly_attracting" TEXT,
    "butterfly_type" TEXT,
    "image" TEXT,
    "image_location" TEXT,
    "image_owner" TEXT,
    "herb_external_have" TEXT,
    "herb_images_change_to" TEXT,
    "notes" TEXT,
    "why_photo_removed" TEXT,
    "why_plant_removed" TEXT,
    "actioned_by" TEXT,
    "date_actioned" TEXT,
    "status" TEXT,
    "imported_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "piante_csv_raw_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "idx_piante_csv_raw_botanical_name" ON "piante_csv_raw"("botanical_name");
